/* Renders the home page, a practice test, or the solutions page, depending on
   <body data-page="home|test|solutions">. Question data comes from
   questions.js (generated by tools/build_questions.py). */

(function () {
  "use strict";

  const TESTS = window.PRACTICE_TESTS;
  const LETTERS = ["A", "B", "C", "D"];
  const page = document.body.dataset.page;
  const params = new URLSearchParams(location.search);

  const $ = (sel, root) => (root || document).querySelector(sel);
  const $$ = (sel, root) => Array.from((root || document).querySelectorAll(sel));
  const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  // ---- per-browser memory (progress + best score). Never required. ----
  const store = {
    get(key) {
      try { return JSON.parse(localStorage.getItem("m4ai-practice:" + key)); } catch (e) { return null; }
    },
    set(key, val) {
      try { localStorage.setItem("m4ai-practice:" + key, JSON.stringify(val)); } catch (e) { /* ignore */ }
    },
  };

  function testNumber() {
    const n = parseInt(params.get("t"), 10);
    return n >= 1 && n <= TESTS.length ? n : 1;
  }

  // ---- chunking document with a character count beside every line ----
  function sepLabel(sep) {
    return sep === "\n\n" ? "\\n\\n" : sep === "\n" ? "\\n" : sep;
  }
  function renderDoc(q) {
    const d = q.doc;
    const settings = q.settings ||
      `Separator <code>${sepLabel(d.sep)}</code> <span>Chunk Size <strong>${d.size}</strong></span>` +
      ` <span>Chunk Overlap <strong>${d.overlap}</strong></span>`;
    const rows = d.text.split("\n").map((line) =>
      `<div class="doc-row"><span class="t">${line ? esc(line) : "&nbsp;"}</span>` +
      `<span class="n">${line ? line.length : ""}</span></div>`).join("");
    return `<div class="doc"><div class="doc-settings">${settings}</div>` +
      `<div class="doc-head"><span>document</span><span>chars</span></div>${rows}</div>`;
  }

  function questionHead(i, q, extra) {
    return `<div class="q-head"><span class="q-num">${i + 1}.</span>` +
      `<span class="q-topic">${esc(q.topic)}</span>${extra || ""}</div>`;
  }

  // ======================================================== HOME
  function home() {
    const list = $("#tests");
    list.innerHTML = TESTS.map((t) => {
      const best = store.get(`best-${t.number}`);
      const meta = best == null ? "10 questions · not attempted yet" : `10 questions · your best: ${best} / 10`;
      return `<li><a class="test-card" href="test.html?t=${t.number}">
        <span class="test-num">${t.number}</span>
        <span><span class="t-title">Practice Test ${t.number}</span><br><span class="t-meta">${meta}</span></span>
        <span class="go">Start →</span></a></li>`;
    }).join("");
    $("#sol-links").innerHTML = TESTS.map((t) =>
      `<a href="solutions.html?t=${t.number}">Test ${t.number} solutions</a>`).join("");
  }

  // ======================================================== TEST
  // State: picks[i] = chosen index or null; graded = null before the first
  // submit, else an array of true/false; retrying = the missed questions are
  // open again; retried = this attempt has used a retry (so it doesn't count
  // toward "your best").
  function test() {
    const n = testNumber();
    const t = TESTS[n - 1];
    const count = t.questions.length;
    const key = `test-${n}`;
    document.title = `Practice Test ${n} · Math for AI`;
    $("#title").textContent = `Practice Test ${n}`;

    const fresh = () => ({ picks: Array(count).fill(null), graded: null, retrying: false, retried: false });
    let s = store.get(key);
    if (!s || !Array.isArray(s.picks) || s.picks.length !== count) s = fresh();
    const save = () => store.set(key, s);
    const isOpen = (i) => !s.graded || (s.retrying && !s.graded[i]);
    const openList = () => t.questions.map((_, i) => i).filter(isOpen);

    const form = $("#questions");
    form.innerHTML = t.questions.map((q, i) => `
      <section class="question" id="q${i + 1}" aria-labelledby="q${i + 1}-label">
        ${questionHead(i, q, '<span class="q-verdict" hidden></span>')}
        <div class="q-body" id="q${i + 1}-label">${q.prompt}${q.doc ? renderDoc(q) : ""}</div>
        <ul class="choices" role="radiogroup">
          ${q.choices.map((c, j) => `
            <li class="choice">
              <input type="radio" name="q${i}" id="q${i}-${j}" value="${j}">
              <label for="q${i}-${j}"><span class="letter">${LETTERS[j]}</span><span class="ctext">${c}</span></label>
            </li>`).join("")}
        </ul>
      </section>`).join("");

    form.addEventListener("change", (e) => {
      if (e.target.type !== "radio") return;
      const i = parseInt(e.target.name.slice(1), 10);
      if (!isOpen(i)) return;
      s.picks[i] = parseInt(e.target.value, 10);
      save();
      progress();
    });

    const submitBtn = $("#submit");
    submitBtn.addEventListener("click", submit);

    function progress() {
      const open = openList();
      const answered = open.filter((i) => s.picks[i] != null).length;
      const bar = $("#progress-text");
      if (!open.length) {
        const score = s.graded.filter(Boolean).length;
        bar.textContent = `Submitted · ${score} / ${count} correct`;
      } else {
        bar.textContent = s.retrying
          ? `${answered} of ${open.length} missed questions re-answered`
          : `${answered} of ${open.length} answered`;
      }
      $("#progress-fill").style.width = (open.length ? 100 * answered / open.length : 100) + "%";
      submitBtn.hidden = !open.length;
    }

    function paint() {
      t.questions.forEach((q, i) => {
        const sec = $(`#q${i + 1}`);
        const verdict = $(".q-verdict", sec);
        const open = isOpen(i);
        $$("input", sec).forEach((inp) => {
          inp.checked = s.picks[i] === parseInt(inp.value, 10);
          inp.disabled = !open;
        });
        sec.classList.remove("is-right", "is-wrong", "locked");
        verdict.hidden = true;
        if (!open) {
          sec.classList.add("locked", s.graded[i] ? "is-right" : "is-wrong");
          verdict.hidden = false;
          verdict.textContent = s.graded[i] ? "Correct" : (s.picks[i] == null ? "Left blank" : "Incorrect");
        }
      });
      progress();
      showScore();
    }

    function submit() {
      const blank = openList().filter((i) => s.picks[i] == null).length;
      if (blank && !confirm(`You left ${blank} question${blank > 1 ? "s" : ""} blank. ` +
        "Blank answers count as wrong. Submit anyway?")) return;
      s.graded = t.questions.map((q, i) => s.picks[i] === q.answer);
      s.retrying = false;
      const score = s.graded.filter(Boolean).length;
      if (!s.retried) {
        const best = store.get(`best-${n}`);
        if (best == null || score > best) store.set(`best-${n}`, score);
      }
      save();
      paint();
      $("#score").scrollIntoView({ behavior: "smooth", block: "start" });
    }

    function showScore() {
      const box = $("#score");
      if (!s.graded || s.retrying) { box.hidden = true; return; }
      const score = s.graded.filter(Boolean).length;
      const missed = s.graded.map((g, i) => g ? null : i + 1).filter((x) => x != null);
      const msg = score === count ? "A perfect paper. Try another test, or come back to this one in a few days."
        : score >= 8 ? "Strong work. Look hard at the ones you missed and find the exact step that went wrong."
        : score >= 6 ? "Getting there. Rework the missed questions on paper before you look at any solutions."
        : "Worth another pass. Reread the practice sections in the textbook, then retry the missed ones.";
      box.hidden = false;
      box.innerHTML = `
        <div class="score-top">
          <div class="score-big">${score}<small> / ${count}</small></div>
          <p class="score-msg">${msg}${s.retried ? " <em>(This score includes retries.)</em>" : ""}</p>
        </div>
        ${missed.length ? `<div class="missed"><span>Missed:</span>${missed.map((m) =>
          `<a href="#q${m}" aria-label="Go to question ${m}">${m}</a>`).join("")}</div>` : ""}
        <div class="score-actions">
          ${missed.length ? '<button type="button" class="btn btn-primary" id="retry">Retry the ones I missed</button>' : ""}
          <button type="button" class="btn" id="restart">Start over</button>
        </div>
        <p class="hint">Missed questions are marked in red below. The correct answers aren't shown here.
          Work them out again on paper, and use the <a href="solutions.html?t=${n}">worked solutions</a> only after you've tried.</p>`;

      const retry = $("#retry");
      if (retry) retry.addEventListener("click", () => {
        s.graded.forEach((g, i) => { if (!g) s.picks[i] = null; });
        s.retrying = true;
        s.retried = true;
        save();
        paint();
        const first = $(`#q${missed[0]}`);
        if (first) first.scrollIntoView({ behavior: "smooth", block: "start" });
      });
      $("#restart").addEventListener("click", () => {
        if (!confirm("Clear every answer and start this test from scratch?")) return;
        s = fresh();
        save();
        paint();
        window.scrollTo({ top: 0, behavior: "smooth" });
      });
    }

    paint();
  }

  // ======================================================== SOLUTIONS
  function solutions() {
    const n = testNumber();
    const t = TESTS[n - 1];
    document.title = `Test ${n} Solutions · Math for AI`;
    $("#title").textContent = `Practice Test ${n} — Solutions`;
    $("#sol-links").innerHTML = TESTS.map((x) =>
      `<a href="solutions.html?t=${x.number}"${x.number === n ? ' aria-current="page"' : ""}>Test ${x.number}</a>`).join("");
    $("#take-link").href = `test.html?t=${n}`;

    $("#solutions").innerHTML = t.questions.map((q, i) => `
      <section class="question sol" id="q${i + 1}">
        ${questionHead(i, q)}
        <div class="q-body">${q.prompt}${q.doc ? renderDoc(q) : ""}</div>
        <ul class="choices">
          ${q.choices.map((c, j) => `
            <li class="choice${j === q.answer ? " correct" : ""}">
              <label><span class="letter">${LETTERS[j]}</span><span class="ctext">${c}</span></label>
            </li>`).join("")}
        </ul>
        <p class="answer-line"><strong>Answer: ${LETTERS[q.answer]}</strong> — ${q.choices[q.answer]}</p>
        <div class="worked"><h4>Worked solution</h4>${q.solution}</div>
        <div class="whynot"><h4>Why not the others</h4><ul>
          ${q.choices.map((c, j) => j === q.answer ? "" :
            `<li><span class="letter-sm">${LETTERS[j]}</span><strong>${c}</strong> — ${q.why[j]}</li>`).join("")}
        </ul></div>
      </section>`).join("");
  }

  if (page === "home") home();
  else if (page === "test") test();
  else if (page === "solutions") solutions();
})();
