/* GENERATED by tools/build_questions.py — do not edit by hand. */
window.PRACTICE_TESTS = [
 {
  "number": 1,
  "questions": [
   {
    "topic": "Vector arithmetic & length",
    "prompt": "<p>Compute 3(2, −1) + (−4, 5).</p>",
    "choices": [
     "(−2, 4)",
     "(2, 2)",
     "(2, 8)",
     "(10, −8)"
    ],
    "answer": 1,
    "why": [
     "Forgot to scale. (2, −1) + (−4, 5) = (−2, 4) — but the 3 multiplies every component of (2, −1) first.",
     null,
     "A sign slip in the second component: 3 × (−1) = −3, and −3 + 5 = 2, not 8.",
     "Subtracted instead of added: (6, −3) − (−4, 5) = (10, −8)."
    ],
    "solution": "<p>Scale first: 3(2, −1) = (6, −3).</p><p>Then add matching components: (6 + (−4), −3 + 5) = <strong>(2, 2)</strong>.</p>"
   },
   {
    "topic": "Vector arithmetic & length",
    "prompt": "<p>Find the length <span class=\"nm\">‖</span>(6, −8)<span class=\"nm\">‖</span>.</p>",
    "choices": [
     "10",
     "14",
     "100",
     "2"
    ],
    "answer": 0,
    "why": [
     null,
     "That is 6 + 8 — adding the sizes of the components. Length squares them first, like Pythagoras.",
     "That is 6² + (−8)² — the right sum, but the square root step is missing.",
     "That is |6 + (−8)| — adding the components with their signs."
    ],
    "solution": "<p>Square, add, square-root: √(6² + (−8)²) = √(36 + 64) = √100 = <strong>10</strong>.</p><p>Squaring makes the minus sign disappear: (−8)² = 64.</p>"
   },
   {
    "topic": "Dot product & cosine similarity",
    "prompt": "<p>Compute the dot product (4, −1) · (2, 3).</p>",
    "choices": [
     "11",
     "(8, −3)",
     "5",
     "15"
    ],
    "answer": 2,
    "why": [
     "A sign slip: (−1)(3) = −3, so it is 8 − 3, not 8 + 3.",
     "Multiplying matching components is only half the job — then add them up. A dot product is a single number, not a vector.",
     null,
     "That is (4 + (−1)) × (2 + 3) — adding inside each vector first. Multiply matching components, then add."
    ],
    "solution": "<p>Multiply matching components and add: (4)(2) + (−1)(3) = 8 − 3 = <strong>5</strong>.</p>"
   },
   {
    "topic": "Dot product & cosine similarity",
    "prompt": "<p>Find the cosine similarity of (3, 4) and (4, 3).</p>",
    "choices": [
     "24",
     "2.4",
     "1",
     "0.96"
    ],
    "answer": 3,
    "why": [
     "That is the dot product. Cosine similarity then divides by both lengths.",
     "That is 24 ÷ (5 + 5). The two lengths get <em>multiplied</em>, not added.",
     "Same numbers, different order — but they point in different directions, so the score is a little below 1.",
     null
    ],
    "solution": "<p>Dot product: (3)(4) + (4)(3) = 24.</p><p>Lengths: <span class=\"nm\">‖</span>(3, 4)<span class=\"nm\">‖</span> = √25 = 5 and <span class=\"nm\">‖</span>(4, 3)<span class=\"nm\">‖</span> = 5.</p><p>Cosine similarity = <span class=\"fr\"><span>24</span><span>5 × 5</span></span> = <span class=\"fr\"><span>24</span><span>25</span></span> = <strong>0.96</strong>. (To get the decimal by hand: <span class=\"fr\"><span>24</span><span>25</span></span> = <span class=\"fr\"><span>96</span><span>100</span></span>.) Very similar directions, but not identical.</p>"
   },
   {
    "topic": "Chunking by hand",
    "prompt": "<p>Give the chunks and their lengths.</p>",
    "choices": [
     "Two chunks: 40 and 39",
     "Two chunks: 39 and 38",
     "Two chunks: 62 and 17",
     "Four chunks: 19, 20, 21, 17"
    ],
    "answer": 0,
    "why": [
     null,
     "Forgot the separator. Gluing two lines together costs one newline: 19 + 20 + 1 = 40.",
     "Chunk 1 went past the Chunk Size. 40 + 21 + 1 = 62 is over 50, so line 3 has to start a new chunk.",
     "The separator decides the atoms, not the chunks. Atoms get glued together until the next one won't fit."
    ],
    "solution": "<p>Atoms: 19, 20, 21, 17.</p><p>Buffer 19. Line 2: 19 + 20 + 1 = 40, not over 50 — it fits.</p><p>Line 3: 40 + 21 + 1 = 62, over 50. <strong>Emit chunk 1 = 40.</strong> Overlap is 0, so pop everything. Buffer takes line 3: 21.</p><p>Line 4: 21 + 17 + 1 = 39, fits. End of text: <strong>emit chunk 2 = 39.</strong></p>",
    "doc": {
     "text": "Doors open at noon.\nSign the guest book.\nFind a seat up front.\nPhones on silent.",
     "sep": "\n",
     "size": 50,
     "overlap": 0
    }
   },
   {
    "topic": "Chunking by hand",
    "prompt": "<p>Which line appears in <strong>both</strong> chunk 1 and chunk 2?</p>",
    "choices": [
     "“Study rooms must be booked.”",
     "“Printing costs ten cents.”",
     "“Food stays in the lobby.”",
     "None — the chunks share no line"
    ],
    "answer": 1,
    "why": [
     "It gets popped. After dropping line 1 the buffer is 53 — still over 30 — so line 2 goes too.",
     null,
     "That line never makes it into chunk 1: 81 + 24 + 1 = 106 is over 100, so it starts chunk 2.",
     "The popping stops at 25, which is not over 30, so line 3 survives into chunk 2."
    ],
    "solution": "<p>Atoms: 27, 27, 25, 24, 24, 23.</p><p>Buffer: 27 → 55 → 81. Line 4: 81 + 24 + 1 = 106, over 100. <strong>Emit chunk 1 = 81</strong> (lines 1–3).</p><p>Pop while over 30: drop line 1 → 81 − 27 − 1 = 53. Still over 30, drop line 2 → 53 − 27 − 1 = 25. Stop. <strong>Line 3, “Printing costs ten cents.”, carries.</strong></p><p>Buffer: 25 → 50 → 75 → 99. End: <strong>emit chunk 2 = 99</strong> (lines 3–6).</p>",
    "doc": {
     "text": "The library opens at eight.\nStudy rooms must be booked.\nPrinting costs ten cents.\nFood stays in the lobby.\nQuiet floor is upstairs.\nReturns go in the slot.",
     "sep": "\n",
     "size": 100,
     "overlap": 30
    }
   },
   {
    "topic": "Chunking edge cases",
    "prompt": "<p>After chunk 1 is emitted, does “Fill the bowl.” carry into chunk 2?</p>",
    "choices": [
     "Yes — after popping line 1 the buffer is exactly 14, which is not over 14",
     "No — with its newline it counts as 15, which is over 14",
     "No — overlap carries at most 14 characters, never a whole line",
     "Yes — but “Sweep the porch.” then won't fit beside it, so it gets popped anyway"
    ],
    "answer": 0,
    "why": [
     null,
     "A single atom in the buffer has no separator. Popping line 1 takes the newline between lines 1 and 2 with it: 28 − 13 − 1 = 14.",
     "Atoms are never split. Overlap carries whole lines or nothing.",
     "Check it: 14 + 1 + 16 = 31, which is not over 32. It fits, so nothing more is popped."
    ],
    "solution": "<p>Atoms: 13, 14, 16, 17.</p><p>Buffer 13 → 13 + 14 + 1 = 28. Line 3: 28 + 16 + 1 = 45, over 32. <strong>Emit chunk 1 = 28.</strong></p><p>Pop while over 14: drop line 1 <em>and the newline that joined it to line 2</em> → 28 − 13 − 1 = 14. 14 is not over 14, so stop. Does line 3 fit beside it? 14 + 1 + 16 = 31, not over 32 — yes.</p><p><strong>Yes, it carries.</strong> The chunks are 28, 31, 17.</p>",
    "doc": {
     "text": "Feed the cat.\nFill the bowl.\nSweep the porch.\nFold the laundry.",
     "sep": "\n",
     "size": 32,
     "overlap": 14
    }
   },
   {
    "topic": "Chunking edge cases",
    "prompt": "<p>Give the chunks.</p>",
    "choices": [
     "32 and 71, sharing “Pack a lunch.”",
     "Three chunks: 18, 13 and 57",
     "32 and 57, with no line shared",
     "32 and 60 — the long line is trimmed to fit"
    ],
    "answer": 2,
    "why": [
     "71 is over the Chunk Size of 60. The popping also continues while the next atom won't fit beside what's left: 13 + 1 + 57 = 71, over 60 — so “Pack a lunch.” has to go.",
     "Lines 1 and 2 fit together: 18 + 13 + 1 = 32, not over 60.",
     null,
     "Atoms are never split. The 57-character line goes in whole."
    ],
    "solution": "<p>Atoms: 18, 13, 57.</p><p>Buffer 18 → 32. Line 3: 32 + 57 + 1 = 90, over 60. <strong>Emit chunk 1 = 32.</strong></p><p>Pop while over 15: drop line 1 → 13. The overlap test is satisfied… but line 3 still has to fit beside it: 13 + 1 + 57 = 71, over 60. So pop again → 0.</p><p>Buffer takes line 3: 57. <strong>Chunks 32 and 57, nothing shared.</strong> Chunk Size wins over overlap.</p>",
    "doc": {
     "text": "Field trip Friday.\nPack a lunch.\nThe bus will leave the school parking lot at seven sharp.",
     "sep": "\n",
     "size": 60,
     "overlap": 15
    }
   },
   {
    "topic": "Precision & recall in search",
    "prompt": "<p>A search engine runs over <strong>20 sentences</strong> from a bike-repair guide. The question is <em>“How do I fix a flat tire?”</em> The answer key marks <strong>5 sentences relevant</strong> (and 15 not relevant). You set <strong>k = 4</strong>, and <strong>3</strong> of the 4 results are relevant.</p><p>What is the <strong>precision</strong>?</p>",
    "choices": [
     "60%",
     "15%",
     "25%",
     "75%"
    ],
    "answer": 3,
    "why": [
     "That is 3 ÷ 5 — dividing by the relevant sentences. That's recall.",
     "That is 3 ÷ 20 — dividing by the whole collection. Precision only asks about what came back.",
     "That is 1 ÷ 4 — the share of the results that was junk, the opposite of precision.",
     null
    ],
    "solution": "<p>Precision = hits ÷ k = 3 ÷ 4 = <strong>75%</strong>. Of the 4 results, 3 were relevant.</p>"
   },
   {
    "topic": "Precision & recall in search",
    "prompt": "<p>A search engine runs over <strong>20 sentences</strong> from a bike-repair guide. The question is <em>“How do I fix a flat tire?”</em> The answer key marks <strong>5 sentences relevant</strong> (and 15 not relevant). You set <strong>k = 4</strong>, and <strong>3</strong> of the 4 results are relevant.</p><p>What is the <strong>recall</strong>?</p>",
    "choices": [
     "75%",
     "60%",
     "15%",
     "20%"
    ],
    "answer": 1,
    "why": [
     "That is 3 ÷ 4 — dividing by k. That's precision.",
     null,
     "That is 3 ÷ 20 — dividing by every sentence in the collection.",
     "That is 3 ÷ 15 — dividing by the not-relevant sentences, which aren't in either formula."
    ],
    "solution": "<p>Recall = hits ÷ relevant = 3 ÷ 5 = <strong>60%</strong>. Of the 5 sentences that could have helped, the search found 3.</p>"
   }
  ]
 },
 {
  "number": 2,
  "questions": [
   {
    "topic": "Vector arithmetic & length",
    "prompt": "<p>Let <b>u</b> = (1, 3) and <b>v</b> = (2, −2). Compute 2<b>u</b> − <b>v</b>.</p>",
    "choices": [
     "(4, 4)",
     "(0, 4)",
     "(0, 8)",
     "(−1, 5)"
    ],
    "answer": 2,
    "why": [
     "That is 2<b>u</b> + <b>v</b>. Subtracting (2, −2) means subtracting 2 and subtracting −2.",
     "A sign slip in the second component: 6 − (−2) = 6 + 2 = 8, not 4.",
     null,
     "That is <b>u</b> − <b>v</b> — the 2 never got applied."
    ],
    "solution": "<p>Scale first: 2<b>u</b> = (2, 6).</p><p>Then subtract: (2 − 2, 6 − (−2)) = <strong>(0, 8)</strong>.</p>"
   },
   {
    "topic": "Vector arithmetic & length",
    "prompt": "<p>A three-word phrase has (2-D) word embeddings (4, 1), (−2, 3) and (1, 5). Mean-pool them into one phrase vector.</p>",
    "choices": [
     "(3, 9)",
     "(1.5, 4.5)",
     "(<span class=\"fr\"><span>7</span><span>3</span></span>, 3)",
     "(1, 3)"
    ],
    "answer": 3,
    "why": [
     "That is the sum. Mean pooling then divides by the number of words, 3.",
     "Divided by 2 — but there are three vectors.",
     "A sign slip: 4 + (−2) + 1 = 3, not 7.",
     null
    ],
    "solution": "<p>Add them: (4 + (−2) + 1, 1 + 3 + 5) = (3, 9).</p><p>Divide by 3: <strong>(1, 3)</strong>.</p>"
   },
   {
    "topic": "Dot product & cosine similarity",
    "prompt": "<p>For what value of <em>k</em> is (2, <em>k</em>) perpendicular to (6, −3)?</p>",
    "choices": [
     "<em>k</em> = 4",
     "<em>k</em> = −4",
     "<em>k</em> = 9",
     "<em>k</em> = <span class=\"fr\"><span>1</span><span>4</span></span>"
    ],
    "answer": 0,
    "why": [
     null,
     "Check it: (2)(6) + (−4)(−3) = 12 + 12 = 24, not 0. Watch the sign on −3.",
     "That is 12 − 3 — the <em>k</em> fell out of the equation.",
     "Solved 3<em>k</em> = 12 upside down: <em>k</em> = 12 ÷ 3, not 3 ÷ 12."
    ],
    "solution": "<p>Perpendicular means the dot product is 0: (2)(6) + (<em>k</em>)(−3) = 12 − 3<em>k</em> = 0.</p><p>So 3<em>k</em> = 12 and <strong><em>k</em> = 4</strong>. Check: (2, 4) · (6, −3) = 12 − 12 = 0. ✓</p>"
   },
   {
    "topic": "Dot product & cosine similarity",
    "prompt": "<p>Using only the <em>sign</em> of the dot product, which pair points in broadly <strong>opposite</strong> directions?</p>",
    "choices": [
     "(1, −2) and (4, 2)",
     "(3, 1) and (1, −2)",
     "(−2, 3) and (4, 1)",
     "(2, 2) and (1, 3)"
    ],
    "answer": 2,
    "why": [
     "(1)(4) + (−2)(2) = 4 − 4 = 0. Zero means perpendicular, not opposite.",
     "(3)(1) + (1)(−2) = 3 − 2 = 1. Positive: same general direction.",
     null,
     "(2)(1) + (2)(3) = 2 + 6 = 8. Positive: same general direction."
    ],
    "solution": "<p>(−2)(4) + (3)(1) = −8 + 3 = <strong>−5</strong>. A negative dot product means broadly opposite directions.</p><p>The other pairs give 0 (perpendicular), 1 and 8 (both same general direction).</p>"
   },
   {
    "topic": "Chunking by hand",
    "prompt": "<p>Give the chunks and their lengths.</p>",
    "choices": [
     "Four chunks: 17, 17, 17, 16",
     "Three chunks: 17, 17, 34",
     "Two chunks: 34 and 33",
     "Two chunks: 35 and 34"
    ],
    "answer": 1,
    "why": [
     "The last two lines do fit together: 17 + 16 + 1 = 34, and 34 is not <em>over</em> 34.",
     null,
     "Forgot the separator. 17 + 17 + 1 = 35 is over 34, so the first two lines can't share a chunk.",
     "A 35-character chunk is over the Chunk Size — lines 1 and 2 don't fit together."
    ],
    "solution": "<p>Atoms: 17, 17, 17, 16.</p><p>Buffer 17. Line 2: 17 + 17 + 1 = 35, over 34. <strong>Emit 17.</strong> Line 3: same thing, <strong>emit 17.</strong></p><p>Buffer 17 (line 3). Line 4: 17 + 16 + 1 = <strong>34</strong> — not <em>over</em> 34, so it fits. End: <strong>emit 34.</strong></p><p><strong>Three chunks: 17, 17, 34.</strong> Landing exactly on the Chunk Size is allowed.</p>",
    "doc": {
     "text": "Charge the robot.\nCheck the wheels.\nLoad the program.\nTest the sensor.",
     "sep": "\n",
     "size": 34,
     "overlap": 0
    }
   },
   {
    "topic": "Chunking by hand",
    "prompt": "<p>How many lines does chunk 2 share with chunk 1?</p>",
    "choices": [
     "None",
     "One — “Judges arrive at nine in the morning.”",
     "About 20 characters of “Judges arrive at nine…”",
     "Two — both lines of chunk 1"
    ],
    "answer": 0,
    "why": [
     null,
     "That line is 37 characters — over the overlap budget of 20 — so it gets popped too.",
     "Atoms are never split. A line carries whole or not at all.",
     "Popping continues while the buffer is over 20, and each line alone is over 20."
    ],
    "solution": "<p>Atoms: 36, 37, 36.</p><p>Buffer 36 → 36 + 37 + 1 = 74. Line 3: 74 + 36 + 1 = 111, over 80. <strong>Emit chunk 1 = 74.</strong></p><p>Pop while over 20: drop line 1 → 37, still over 20; drop line 2 → 0. Buffer takes line 3. <strong>Emit chunk 2 = 36.</strong></p><p><strong>Zero overlap</strong>, even with Chunk Overlap set to 20: every line is bigger than 20, and you can't keep part of a line.</p>",
    "doc": {
     "text": "The science fair is held in the gym.\nJudges arrive at nine in the morning.\nPosters must be taped to the tables.",
     "sep": "\n",
     "size": 80,
     "overlap": 20
    }
   },
   {
    "topic": "Chunking edge cases",
    "prompt": "<p>The two short lines are 11 characters each, and Chunk Overlap is 22. How many of them carry into chunk 2?</p>",
    "choices": [
     "Both — 11 + 11 = 22, which is not over 22",
     "One — “Charge bots”",
     "None",
     "One — “Bring tools”"
    ],
    "answer": 1,
    "why": [
     "Two lines in the buffer have a newline between them: 11 + 1 + 11 = 23, which <em>is</em> over 22.",
     null,
     "After dropping “Bring tools” the buffer is 11, not over 22 — and 11 + 1 + 33 = 45 fits. So “Charge bots” stays.",
     "Popping always removes from the <em>front</em>, so the earlier line, “Bring tools”, is the one that goes."
    ],
    "solution": "<p>Atoms: 25, 11, 11, 33.</p><p>Buffer 25 → 37 → 49. Line 4: 49 + 33 + 1 = 83, over 60. <strong>Emit chunk 1 = 49.</strong></p><p>Pop while over 22: drop line 1 → 49 − 25 − 1 = 23. That's 11 + 1 + 11 — the newline between the short lines counts — so it is still over 22. Drop “Bring tools” → 11. Stop. Line 4 fits: 11 + 1 + 33 = 45.</p><p><strong>Only one line, “Charge bots”, carries.</strong> Chunks: 49 and 45.</p>",
    "doc": {
     "text": "Welcome to robotics club.\nBring tools\nCharge bots\nThe competition is next Saturday.",
     "sep": "\n",
     "size": 60,
     "overlap": 22
    }
   },
   {
    "topic": "Chunking edge cases",
    "prompt": "<p>Give the chunks. (Careful: what is the separator here?)</p>",
    "choices": [
     "46 and 30",
     "48 and 47",
     "44 and 43",
     "48 and 31"
    ],
    "answer": 3,
    "why": [
     "Counted each separator as 1 character. <code>\\n\\n</code> is two characters, so every join costs 2.",
     "Stopped popping at 32 — but 32 is over 30, so “Bring a smock.” has to go too.",
     "Left the separators out altogether.",
     null
    ],
    "solution": "<p>Atoms: 14, 14, 16, 13. The blank lines are the separators, and each is <strong>2</strong> characters.</p><p>Buffer 14 → 14 + 14 + 2 = 30 → 30 + 16 + 2 = 48. Atom 4: 48 + 13 + 2 = 63, over 50. <strong>Emit chunk 1 = 48.</strong></p><p>Pop while over 30: drop atom 1 → 48 − 14 − 2 = 32, still over 30; drop atom 2 → 16. Stop.</p><p>Add atom 4: 16 + 2 + 13 = 31. <strong>Chunks 48 and 31</strong>, sharing “Paint the mural.”</p>",
    "doc": {
     "text": "Art is Monday.\n\nBring a smock.\n\nPaint the mural.\n\nWash brushes.",
     "sep": "\n\n",
     "size": 50,
     "overlap": 30
    }
   },
   {
    "topic": "Precision & recall in search",
    "prompt": "<p>A search engine runs over <strong>40 sentences</strong> from a campus FAQ. The question is <em>“When is the library open?”</em> The answer key marks <strong>4 sentences relevant</strong> (and 36 not relevant). You set <strong>k = 10</strong>, and <strong>2</strong> of the 10 results are relevant.</p><p>What was the <strong>best possible precision</strong> at this k?</p>",
    "choices": [
     "100%",
     "20%",
     "40%",
     "10%"
    ],
    "answer": 2,
    "why": [
     "Assumes a perfect score is always reachable. Only 4 relevant sentences exist, so a perfect search still fills 6 of the 10 slots with junk.",
     "That is 2 ÷ 10 — the precision this search <em>actually</em> got, not the best it could get.",
     null,
     "That is 4 ÷ 40 — relevant over the whole collection."
    ],
    "solution": "<p>Best possible hits = the smaller of k (10) and relevant (4) = 4.</p><p>Best possible precision = 4 ÷ 10 = <strong>40%</strong>.</p>"
   },
   {
    "topic": "Precision & recall in search",
    "prompt": "<p>A search engine runs over <strong>40 sentences</strong> from a campus FAQ. The question is <em>“When is the library open?”</em> The answer key marks <strong>4 sentences relevant</strong> (and 36 not relevant). You set <strong>k = 10</strong>, and <strong>2</strong> of the 10 results are relevant.</p><p>What is the <strong>recall</strong>?</p>",
    "choices": [
     "50%",
     "20%",
     "5%",
     "100%"
    ],
    "answer": 0,
    "why": [
     null,
     "That is 2 ÷ 10 — dividing by k. That's precision.",
     "That is 2 ÷ 40 — dividing by the whole collection.",
     "That's the <em>best possible</em> recall at k = 10 (4 ÷ 4), not what this search got."
    ],
    "solution": "<p>Recall = hits ÷ relevant = 2 ÷ 4 = <strong>50%</strong>. Half of the relevant sentences were found.</p>"
   }
  ]
 },
 {
  "number": 3,
  "questions": [
   {
    "topic": "Vector arithmetic & length",
    "prompt": "<p>Find the length of the 3-D vector (2, −3, 6).</p>",
    "choices": [
     "11",
     "5",
     "49",
     "7"
    ],
    "answer": 3,
    "why": [
     "That is 2 + 3 + 6 — adding the sizes of the components instead of squaring them.",
     "That is 2 + (−3) + 6 — adding the components with their signs.",
     "That is 4 + 9 + 36 — the right sum, but the square root is missing.",
     null
    ],
    "solution": "<p>Same rule as 2-D, one more squared term: √(2² + (−3)² + 6²) = √(4 + 9 + 36) = √49 = <strong>7</strong>.</p>"
   },
   {
    "topic": "Vector arithmetic & length",
    "prompt": "<p>Suppose <span class=\"nm\">‖</span><b>v</b><span class=\"nm\">‖</span> = 6. <em>Without</em> knowing the components of <b>v</b>, find <span class=\"nm\">‖</span>−3<b>v</b><span class=\"nm\">‖</span>.</p>",
    "choices": [
     "18",
     "−18",
     "2",
     "54"
    ],
    "answer": 0,
    "why": [
     null,
     "A length is never negative. The rule is <span class=\"nm\">‖</span>c<b>v</b><span class=\"nm\">‖</span> = |c| <span class=\"nm\">‖</span><b>v</b><span class=\"nm\">‖</span>.",
     "Divided by 3 instead of multiplying.",
     "Multiplied by 3² = 9. Every component gets multiplied by −3, so the length gets multiplied by |−3| = 3."
    ],
    "solution": "<p><span class=\"nm\">‖</span>c<b>v</b><span class=\"nm\">‖</span> = |c| <span class=\"nm\">‖</span><b>v</b><span class=\"nm\">‖</span>, so <span class=\"nm\">‖</span>−3<b>v</b><span class=\"nm\">‖</span> = |−3| × 6 = <strong>18</strong>.</p><p>The minus sign flips the direction but doesn't change the length.</p>"
   },
   {
    "topic": "Dot product & cosine similarity",
    "prompt": "<p>Compute the 3-D dot product (2, −1, 3) · (1, 4, 2).</p>",
    "choices": [
     "12",
     "4",
     "11",
     "(2, −4, 6)"
    ],
    "answer": 1,
    "why": [
     "A sign slip: (−1)(4) = −4, so it's 2 − 4 + 6.",
     null,
     "Added all six numbers together. Multiply matching components first, then add.",
     "Multiplied matching components but never added them. A dot product is one number."
    ],
    "solution": "<p>(2)(1) + (−1)(4) + (3)(2) = 2 − 4 + 6 = <strong>4</strong>.</p>"
   },
   {
    "topic": "Dot product & cosine similarity",
    "prompt": "<p>A vector <b>u</b> has <b>u</b> · <b>u</b> = 49. What is <span class=\"nm\">‖</span><b>u</b><span class=\"nm\">‖</span>?</p>",
    "choices": [
     "7",
     "49",
     "24.5",
     "−7"
    ],
    "answer": 0,
    "why": [
     null,
     "A vector dotted with itself is its length <em>squared</em>. Take the square root.",
     "Halved instead of taking the square root.",
     "Lengths are never negative."
    ],
    "solution": "<p><b>u</b> · <b>u</b> = <span class=\"nm\">‖</span><b>u</b><span class=\"nm\">‖</span>², so <span class=\"nm\">‖</span><b>u</b><span class=\"nm\">‖</span> = √49 = <strong>7</strong>.</p>"
   },
   {
    "topic": "Chunking by hand",
    "prompt": "<p>Give the chunks.</p>",
    "choices": [
     "Three chunks: 10, 60 and 30",
     "Two chunks: 10 and 60 — the rest of the paragraph is dropped",
     "Two chunks: 10 and 90 — the second is longer than the Chunk Size",
     "No chunks — Split Text reports an error"
    ],
    "answer": 2,
    "why": [
     "Split Text never cuts an atom. The whole paragraph is one atom, so it goes into a chunk in one piece.",
     "Nothing is ever thrown away.",
     null,
     "It doesn't error. It emits the oversized chunk and only writes a warning to its log."
    ],
    "solution": "<p>The separator is <code>\\n\\n</code>, so the blank line is the cut. Atoms: 10 and 90.</p><p>Buffer 10. Atom 2: 10 + 90 + 2 = 102, over 60. <strong>Emit chunk 1 = 10.</strong> Pop → empty. Buffer takes atom 2: 90. End: <strong>emit chunk 2 = 90.</strong></p><p>That's 30 over the Chunk Size, and Split Text lets it happen. Lowering Chunk Size wouldn't help — only a finer <strong>Separator</strong> can break up a paragraph.</p>",
    "doc": {
     "text": "Lab rules.\n\nEvery student must wear goggles whenever a burner is lit, and long hair must be tied back.",
     "sep": "\n\n",
     "size": 60,
     "overlap": 5
    }
   },
   {
    "topic": "Chunking by hand",
    "prompt": "<p>A word list, one word per line. What is chunk 1?</p>",
    "choices": [
     "just cat",
     "cat and dog together",
     "cat, dog and bird together",
     "cat, dog, bird and fish together"
    ],
    "answer": 2,
    "why": [
     "Chunk Size 12 isn't “one word”. The buffer keeps gluing while the next word fits.",
     "Adding bird: 7 + 4 + 1 = 12, and 12 is not <em>over</em> 12 — it fits.",
     null,
     "Adding fish: 12 + 4 + 1 = 17, over 12."
    ],
    "solution": "<p>Atoms: 3, 3, 4, 4, 4, 3.</p><p>Buffer 3 → 3 + 3 + 1 = 7 → 7 + 4 + 1 = <strong>12</strong> (exactly the Chunk Size, which is allowed). Fish: 12 + 4 + 1 = 17, over 12. <strong>Emit chunk 1 = “cat, dog, bird”</strong> (12 characters).</p><p>The whole run gives three chunks: cat/dog/bird, fish/frog, bee.</p>",
    "doc": {
     "text": "cat\ndog\nbird\nfish\nfrog\nbee",
     "sep": "\n",
     "size": 12,
     "overlap": 0
    }
   },
   {
    "topic": "Chunking edge cases",
    "prompt": "<p>How many lines does chunk 2 share with chunk 1?</p>",
    "choices": [
     "Two — “Bring shin guards.” and “Fill a bottle.”",
     "None",
     "Three — all of chunk 1",
     "One — “Fill a bottle.”"
    ],
    "answer": 3,
    "why": [
     "After dropping line 1 the buffer is 33, which passes the overlap test — but 33 + 1 + 44 = 78 is over 60, so the popping keeps going.",
     "After dropping line 2 the buffer is 14, and 14 + 1 + 44 = 59 fits. So “Fill a bottle.” stays.",
     "Chunk 1 is 50 characters, over the overlap of 35; at least line 1 has to go.",
     null
    ],
    "solution": "<p>Atoms: 16, 18, 14, 44.</p><p>Buffer 16 → 35 → 50. Line 4: 50 + 44 + 1 = 95, over 60. <strong>Emit chunk 1 = 50.</strong></p><p>Pop: drop line 1 → 33. That's not over 35, <em>but</em> line 4 has to fit beside it: 33 + 1 + 44 = 78, over 60. Pop again → 14. Now 14 + 1 + 44 = 59, which fits. Stop.</p><p><strong>One line carries.</strong> Chunks: 50 and 59. The overlap allowed two lines; the Chunk Size only had room for one.</p>",
    "doc": {
     "text": "Soccer practice.\nBring shin guards.\nFill a bottle.\nThe coach will run sprint drills at the end.",
     "sep": "\n",
     "size": 60,
     "overlap": 35
    }
   },
   {
    "topic": "Chunking edge cases",
    "prompt": "<p>How long is chunk 2?</p>",
    "choices": [
     "42",
     "58",
     "57",
     "31"
    ],
    "answer": 1,
    "why": [
     "Popped “Grease the pan.” because 15 + 1 + 42 = 58 — but 58 is not <em>over</em> 58, so it fits and stays.",
     null,
     "Forgot the newline that joins the carried line to the new one.",
     "That's chunk 1."
    ],
    "solution": "<p>Atoms: 15, 15, 42.</p><p>Buffer 15 → 31. Line 3: 31 + 42 + 1 = 74, over 58. <strong>Emit chunk 1 = 31.</strong></p><p>Pop while over 15: drop line 1 → 15. Stop. Does line 3 fit beside it? 15 + 1 + 42 = <strong>58</strong>, not over 58 — yes.</p><p><strong>Chunk 2 = 58.</strong> Both checks in the popping are strictly “bigger than”.</p>",
    "doc": {
     "text": "Mix the batter.\nGrease the pan.\nBake it for thirty minutes at three fifty.",
     "sep": "\n",
     "size": 58,
     "overlap": 15
    }
   },
   {
    "topic": "Precision & recall in search",
    "prompt": "<p>Your search returns <strong>k = 10</strong> results. Precision is <strong>40%</strong> and recall is <strong>80%</strong>. How many sentences does the answer key mark as relevant?</p>",
    "choices": [
     "4",
     "5",
     "8",
     "25"
    ],
    "answer": 1,
    "why": [
     "That's the number of hits — one step early.",
     null,
     "That's 80% of 10 — using k where hits belongs.",
     "That's 10 ÷ 40%, which doesn't mean anything here."
    ],
    "solution": "<p>Precision = hits ÷ k, so 40% = hits ÷ 10, and hits = 4.</p><p>Recall = hits ÷ relevant, so 80% = 4 ÷ relevant. 4 is 80% of what? <strong>5.</strong></p>"
   },
   {
    "topic": "Precision & recall in search",
    "prompt": "<p>A question has <strong>6 relevant</strong> sentences in a collection of <strong>30</strong>. Which k lets a perfect search score 100% on <strong>both</strong> precision and recall?</p>",
    "choices": [
     "k = 1",
     "k = 10",
     "k = 30",
     "k = 6"
    ],
    "answer": 3,
    "why": [
     "Best precision is 1 ÷ 1 = 100%, but best recall is only 1 ÷ 6.",
     "Best recall is 100%, but best precision is only 6 ÷ 10 = 60%.",
     "Returning everything guarantees 100% recall, but best precision is only 6 ÷ 30 = 20%.",
     null
    ],
    "solution": "<p>When k equals the number of relevant sentences, best possible hits = 6, so best precision = 6 ÷ 6 and best recall = 6 ÷ 6. <strong>k = 6</strong> is the only setting where both can reach 100%.</p>"
   }
  ]
 },
 {
  "number": 4,
  "questions": [
   {
    "topic": "Vector arithmetic & length",
    "prompt": "<p>Find the unit vector pointing the same way as (−5, 12).</p>",
    "choices": [
     "(−<span class=\"fr\"><span>5</span><span>13</span></span>, <span class=\"fr\"><span>12</span><span>13</span></span>)",
     "(−<span class=\"fr\"><span>5</span><span>7</span></span>, <span class=\"fr\"><span>12</span><span>7</span></span>)",
     "(<span class=\"fr\"><span>5</span><span>13</span></span>, <span class=\"fr\"><span>12</span><span>13</span></span>)",
     "(−<span class=\"fr\"><span>5</span><span>17</span></span>, <span class=\"fr\"><span>12</span><span>17</span></span>)"
    ],
    "answer": 0,
    "why": [
     null,
     "Divided by −5 + 12 = 7. Divide by the <em>length</em>.",
     "Dropped the minus sign — that vector points a different way.",
     "Divided by 5 + 12 = 17. Divide by the length, √(25 + 144)."
    ],
    "solution": "<p>Length: √((−5)² + 12²) = √(25 + 144) = √169 = 13.</p><p>Divide every component by 13: <strong>(−<span class=\"fr\"><span>5</span><span>13</span></span>, <span class=\"fr\"><span>12</span><span>13</span></span>)</strong>.</p>"
   },
   {
    "topic": "Vector arithmetic & length",
    "prompt": "<p>Let <b>u</b> = (5, 0) and <b>v</b> = (0, 12). Find <span class=\"nm\">‖</span><b>u</b> + <b>v</b><span class=\"nm\">‖</span>.</p>",
    "choices": [
     "17",
     "13",
     "169",
     "√17"
    ],
    "answer": 1,
    "why": [
     "That's <span class=\"nm\">‖</span><b>u</b><span class=\"nm\">‖</span> + <span class=\"nm\">‖</span><b>v</b><span class=\"nm\">‖</span> = 5 + 12. The length of a sum is generally <em>not</em> the sum of the lengths.",
     null,
     "That's 25 + 144 — the square root is missing.",
     "Added 5 + 12 and then took the root. Square each component first."
    ],
    "solution": "<p><b>u</b> + <b>v</b> = (5, 12), so <span class=\"nm\">‖</span><b>u</b> + <b>v</b><span class=\"nm\">‖</span> = √(25 + 144) = √169 = <strong>13</strong>.</p><p>Compare 5 + 12 = 17: the straight path is shorter than the detour.</p>"
   },
   {
    "topic": "Dot product & cosine similarity",
    "prompt": "<p>Two vectors <b>u</b> and <b>v</b> have cosine similarity 0.6. What is the cosine similarity of 5<b>u</b> and −2<b>v</b>?</p>",
    "choices": [
     "0.6",
     "−6",
     "−1.2",
     "−0.6"
    ],
    "answer": 3,
    "why": [
     "Stretching doesn't change cosine similarity — but the minus sign in −2<b>v</b> flips it to point the opposite way.",
     "Multiplied 0.6 by 5 and by −2. Cosine similarity ignores length, and it can never go below −1.",
     "Multiplied by −2. Cosine similarity ignores length, and it can never go below −1.",
     null
    ],
    "solution": "<p>Cosine similarity ignores length, so the 5 and the 2 don't matter. The minus sign reverses the direction of <b>v</b>, which flips the sign of the score: <strong>−0.6</strong>.</p>"
   },
   {
    "topic": "Dot product & cosine similarity",
    "prompt": "<p>Find the cosine similarity of (2, 0) and (0, −7).</p>",
    "choices": [
     "−1",
     "1",
     "0",
     "−14"
    ],
    "answer": 2,
    "why": [
     "A minus sign on a component doesn't make two vectors opposite. The dot product here is 0.",
     "Check the dot product: (2)(0) + (0)(−7) = 0.",
     null,
     "That's (2)(−7) — multiplying components that don't match up."
    ],
    "solution": "<p>Dot product: (2)(0) + (0)(−7) = 0. Zero divided by anything is 0, so the cosine similarity is <strong>0</strong>.</p><p>One points along the horizontal axis, the other straight down: perpendicular.</p>"
   },
   {
    "topic": "Chunking by hand",
    "prompt": "<p>Chunk Size <strong>40</strong> and Chunk Overlap <strong>15</strong> for both runs. Run it once with Separator <code>\\n\\n</code> and once with Separator <code>\\n</code>. How many chunks does each run make?</p>",
    "choices": [
     "<code>\\n\\n</code>: 2 chunks · <code>\\n</code>: 3 chunks",
     "<code>\\n\\n</code>: 2 chunks · <code>\\n</code>: 4 chunks",
     "<code>\\n\\n</code>: 1 chunk · <code>\\n</code>: 3 chunks",
     "Both runs make 2 chunks"
    ],
    "answer": 0,
    "why": [
     null,
     "With <code>\\n</code>, lines get glued: 19 + 14 + 1 = 34 fits under 40. Four atoms doesn't mean four chunks.",
     "The two paragraphs are 34 and 38; together that's 34 + 38 + 2 = 74, over 40.",
     "With <code>\\n</code>, a line carries over as overlap, which pushes the last line into a third chunk."
    ],
    "solution": "<p><strong>With <code>\\n\\n</code>:</strong> two atoms, each a whole paragraph with its newline inside: 19 + 1 + 14 = 34 and 19 + 1 + 18 = 38. 34 + 38 + 2 = 74 is over 40, so <strong>2 chunks: 34 and 38</strong>, no overlap.</p><p><strong>With <code>\\n</code>:</strong> atoms 19, 14, 19, 18 (the blank line is an empty piece and gets dropped). 19 → 34; next: 34 + 19 + 1 = 54, over 40, emit 34. Pop to 14 (“Bring a snack.” carries). 14 + 19 + 1 = 34; next: 53, over 40, emit 34. Pop: 34 − 14 − 1 = 19, over 15, pop → 0. Last line: 18. <strong>3 chunks: 34, 34, 18.</strong></p>",
    "doc": {
     "text": "Games start at six.\nBring a snack.\n\nThe gym doors lock.\nUse the side door.",
     "sep": "\n",
     "size": 40,
     "overlap": 15
    },
    "settings": "Chunk Size <strong>40</strong> · Chunk Overlap <strong>15</strong> · two runs, two separators"
   },
   {
    "topic": "Chunking by hand",
    "prompt": "<p>How many chunks come out, and how many lines does chunk 2 share with chunk 1?</p>",
    "choices": [
     "2 chunks; no lines shared",
     "2 chunks; chunk 2 shares 1 line",
     "7 chunks, one per line",
     "3 chunks; chunk 2 shares 2 lines"
    ],
    "answer": 3,
    "why": [
     "That's what happens with no overlap at all. Chunk Overlap 24 lets lines carry.",
     "After two pops the buffer is exactly 24 — not <em>over</em> 24 — so popping stops there, with two lines.",
     "The separator makes atoms, not chunks. Short lines get glued together.",
     null
    ],
    "solution": "<p>Atoms: 11, 12, 11, 12, 11, 10, 11.</p><p>Buffer: 11 → 24 → 36 → 49. Line 5: 49 + 11 + 1 = 61, over 50. <strong>Emit chunk 1 = 49.</strong> Pop while over 24: → 37 → <strong>24</strong>. Stop. Lines 3 and 4 carry.</p><p>Buffer: 24 → 36 → 47. Line 7: 47 + 11 + 1 = 59, over 50. <strong>Emit chunk 2 = 47.</strong> Pop: → 35 → 22. Lines 5 and 6 carry. 22 + 11 + 1 = 34. End: <strong>emit chunk 3 = 34.</strong></p><p><strong>3 chunks; each shares 2 lines with the one before.</strong></p>",
    "doc": {
     "text": "Plug it in.\nPress start.\nWait a bit.\nPick a song.\nTurn it up.\nDance now.\nRest after.",
     "sep": "\n",
     "size": 50,
     "overlap": 24
    }
   },
   {
    "topic": "Chunking edge cases",
    "prompt": "<p>A classmate's work: <em>“Atoms 21, 17, 50. Chunk 1 = 39. Pop while over 17: drop line 1, leaving 17. Stop, so ‘Show your ticket.’ carries. Add line 3: 17 + 1 + 50 = 68. Chunks: 39 and 68.”</em></p><p>What went wrong?</p>",
    "choices": [
     "Nothing — 17 is not over 17, so the line carries",
     "They forgot a newline when popping: the buffer is really 18, so the line goes. Chunks: 39 and 50.",
     "They stopped popping too soon: 17 + 1 + 50 = 68 is over 60, so “Show your ticket.” must go too. Chunks: 39 and 50.",
     "Chunk 1 is wrong: it should be 38"
    ],
    "answer": 2,
    "why": [
     "The overlap test passes, but the popping also checks that the next atom fits: 68 is over 60.",
     "Right chunks, wrong reason. Popping line 1 takes its newline with it — the buffer really is 17.",
     null,
     "Two lines joined need one newline: 21 + 17 + 1 = 39."
    ],
    "solution": "<p>The warning sign is in their own answer: a 68-character chunk with Chunk Size 60, when no single line is anywhere near 60.</p><p>After popping to 17, the overlap test is satisfied, but line 3 has to fit beside it: 17 + 1 + 50 = 68, over 60. So “Show your ticket.” is dropped too. <strong>Chunks: 39 and 50, nothing shared.</strong></p>",
    "doc": {
     "text": "Check in at the gate.\nShow your ticket.\nThe parade starts at the corner of Main and Fifth.",
     "sep": "\n",
     "size": 60,
     "overlap": 17
    }
   },
   {
    "topic": "Chunking edge cases",
    "prompt": "<p>Chunk 1 is the first three lines, 39 characters. Popping begins. Right after “Grab a tray.” is dropped, how big is the buffer?</p>",
    "choices": [
     "25",
     "26",
     "27",
     "13"
    ],
    "answer": 1,
    "why": [
     "Left out the newline between the two lines still in the buffer: 12 + 1 + 13 = 26.",
     null,
     "39 − 12 forgets that the newline after “Grab a tray.” leaves with it: 39 − 12 − 1 = 26.",
     "That's after a <em>second</em> pop. The question asks about right after the first."
    ],
    "solution": "<p>Atoms: 12, 12, 13, 32. Chunk 1 = 12 + 12 + 13 + 2 newlines = 39.</p><p>Dropping “Grab a tray.” removes 12 characters <em>and</em> the newline that joined it to line 2: 39 − 12 − 1 = <strong>26</strong>. (Check: what's left is “Take a fork.” + newline + “Pick a drink.” = 12 + 1 + 13 = 26.)</p><p>For the record: 26 is over 25, so popping continues; the final chunks are 39 and 32.</p>",
    "doc": {
     "text": "Grab a tray.\nTake a fork.\nPick a drink.\nPay at the register by the door.",
     "sep": "\n",
     "size": 45,
     "overlap": 25
    }
   },
   {
    "topic": "Precision & recall in search",
    "prompt": "<p>An answer key marks <strong>6 sentences relevant</strong> and <strong>4 not relevant</strong> (10 in all). Which of these results <strong>could not</strong> happen?</p>",
    "choices": [
     "Return 8 results and get 3 hits",
     "Return 4 results and get 0 hits",
     "Return 10 results and get 6 hits",
     "Return 3 results and get 3 hits"
    ],
    "answer": 0,
    "why": [
     null,
     "Possible: all 4 not-relevant sentences come back. A terrible search, but a possible one.",
     "Possible — in fact certain. Returning everything returns all 6 relevant sentences.",
     "Possible: 6 relevant sentences exist, so 3 of them can all come back."
    ],
    "solution": "<p>8 results with 3 hits means 5 results were not relevant — but only 4 not-relevant sentences exist. Return 8 and at least 8 − 4 = 4 must be relevant.</p><p>That's the one job of the not-relevant count: it's in neither formula, but it tells you which results are possible at all.</p>"
   },
   {
    "topic": "Precision & recall in search",
    "prompt": "<p>A search engine runs over <strong>25 sentences</strong>. The answer key marks <strong>10 relevant</strong> (15 not). You set <strong>k = 5</strong>, and <strong>3</strong> of the 5 results are relevant.</p><p>What was the <strong>best possible recall</strong> at this k?</p>",
    "choices": [
     "100%",
     "30%",
     "50%",
     "20%"
    ],
    "answer": 2,
    "why": [
     "With only 5 slots, at least 5 of the 10 relevant sentences are always left out.",
     "That's 3 ÷ 10 — the recall this search actually got, not the best it could get.",
     null,
     "That's 5 ÷ 25 — k over the whole collection."
    ],
    "solution": "<p>Best possible hits = the smaller of k (5) and relevant (10) = 5.</p><p>Best possible recall = 5 ÷ 10 = <strong>50%</strong>. This search got 30% against a ceiling of 50%.</p>"
   }
  ]
 },
 {
  "number": 5,
  "questions": [
   {
    "topic": "Vector arithmetic & length",
    "prompt": "<p>Find <span class=\"nm\">‖</span>(−2, 4)<span class=\"nm\">‖</span>. Leave it as a square root if it isn't a whole number.</p>",
    "choices": [
     "6",
     "√12",
     "√20 (which is also 2√5)",
     "20"
    ],
    "answer": 2,
    "why": [
     "That's 2 + 4 — adding the sizes of the components.",
     "(−2)² is +4, not −4. The slip gives 16 − 4 = 12.",
     null,
     "The right sum, but the square root is missing."
    ],
    "solution": "<p>√((−2)² + 4²) = √(4 + 16) = <strong>√20</strong>. It isn't a whole number, so leave it as a root (it simplifies to 2√5, since 20 = 4 × 5).</p>"
   },
   {
    "topic": "Vector arithmetic & length",
    "prompt": "<p>Which of these is a <strong>unit vector</strong> (length exactly 1)?</p>",
    "choices": [
     "(0.5, 0.5)",
     "(1, 1)",
     "(0.3, 0.7)",
     "(0.6, −0.8)"
    ],
    "answer": 3,
    "why": [
     "Length √(0.25 + 0.25) = √0.5, which is less than 1.",
     "Length √(1 + 1) = √2, more than 1.",
     "The components add to 1 — that's what a <em>probability distribution</em> needs, not a unit vector. Length √(0.09 + 0.49) = √0.58, less than 1.",
     null
    ],
    "solution": "<p><span class=\"nm\">‖</span>(0.6, −0.8)<span class=\"nm\">‖</span> = √(0.36 + 0.64) = √1 = <strong>1</strong>.</p><p>A unit vector's squared components add to 1. A distribution's plain components add to 1. Different rules.</p>"
   },
   {
    "topic": "Dot product & cosine similarity",
    "prompt": "<p>Every word vector below has length 1. Word A = (0.8, 0.6). Which word is <strong>most similar</strong> to A?</p>",
    "choices": [
     "(1, 0)",
     "(0.6, 0.8)",
     "(0, 1)",
     "(−0.8, −0.6)"
    ],
    "answer": 1,
    "why": [
     "Similarity (0.8)(1) + (0.6)(0) = 0.8. Close, but 0.96 beats it.",
     null,
     "Similarity (0.8)(0) + (0.6)(1) = 0.6.",
     "Similarity −0.64 − 0.36 = −1: the exact opposite direction."
    ],
    "solution": "<p>They're all unit vectors, so cosine similarity is just the dot product — no dividing.</p><p>(0.8)(0.6) + (0.6)(0.8) = 0.48 + 0.48 = <strong>0.96</strong>, the biggest of the four (the others give 0.8, 0.6 and −1).</p>"
   },
   {
    "topic": "Dot product & cosine similarity",
    "prompt": "<p>Find the cosine similarity of (1, 2, 2) and (2, 1, 2).</p>",
    "choices": [
     "<span class=\"fr\"><span>8</span><span>9</span></span>",
     "8",
     "<span class=\"fr\"><span>4</span><span>3</span></span>",
     "1"
    ],
    "answer": 0,
    "why": [
     null,
     "That's the dot product. Now divide by both lengths.",
     "That's 8 ÷ (3 + 3). Multiply the lengths, don't add them. (And a cosine similarity can never be bigger than 1.)",
     "Same numbers in a different order — different directions, so the score is below 1."
    ],
    "solution": "<p>Dot product: (1)(2) + (2)(1) + (2)(2) = 2 + 2 + 4 = 8.</p><p>Lengths: √(1 + 4 + 4) = 3 and √(4 + 1 + 4) = 3.</p><p>Cosine similarity = <span class=\"fr\"><span>8</span><span>3 × 3</span></span> = <strong><span class=\"fr\"><span>8</span><span>9</span></span></strong>.</p>"
   },
   {
    "topic": "Chunking by hand",
    "prompt": "<p>A classmate builds the Lab 6 word-search flow with Separator <code>\\n</code>, Chunk Size <strong>1000</strong> and Chunk Overlap <strong>0</strong>, on a file with one word per line. Every search returns one giant chunk holding every word. Which <strong>one</strong> change fixes it?</p>",
    "choices": [
     "Set Chunk Overlap to 1",
     "Set Chunk Size to 1",
     "Empty out the Separator box",
     "Set the Separator to <code>\\n\\n</code>"
    ],
    "answer": 1,
    "why": [
     "Overlap only controls what carries between chunks. With one chunk, there's nothing to carry.",
     null,
     "With no separator, the splitter cuts between every character — and at Chunk Size 1000 it glues them right back into one blob.",
     "A one-word-per-line file has no blank lines, so the whole file becomes a single atom."
    ],
    "solution": "<p>The cut is fine: <code>\\n</code> gives one atom per word. The problem is the glue: a short word list is nowhere near 1000 characters, so every word fits in the same buffer and one chunk comes out.</p><p><strong>Chunk Size 1</strong> means no two words can ever fit together, so every word becomes its own chunk — and since atoms are never split, you get whole words, not letters.</p>"
   },
   {
    "topic": "Chunking by hand",
    "prompt": "<p>How long is chunk 2?</p>",
    "choices": [
     "32",
     "45",
     "39",
     "41"
    ],
    "answer": 3,
    "why": [
     "That's what happens with no overlap. Here “Warm up.” carries into chunk 2.",
     "Chunk Size is a ceiling you bump into, not a length you hit.",
     "Left out the newlines: 8 + 19 + 12 = 39, but the three lines need two newlines between them.",
     null
    ],
    "solution": "<p>Atoms: 13, 15, 8, 19, 12, 16.</p><p>Buffer: 13 → 29 → 38. Line 4: 38 + 19 + 1 = 58, over 45. <strong>Emit chunk 1 = 38.</strong></p><p>Pop while over 20: → 24 → 8. Stop. “Warm up.” carries.</p><p>Buffer: 8 → 8 + 19 + 1 = 28 → 28 + 12 + 1 = 41. Line 6: 41 + 16 + 1 = 58, over 45. <strong>Emit chunk 2 = 41.</strong></p>",
    "doc": {
     "text": "Arrive early.\nFind your team.\nWarm up.\nPlay four quarters.\nShake hands.\nClean the bench.",
     "sep": "\n",
     "size": 45,
     "overlap": 20
    }
   },
   {
    "topic": "Chunking edge cases",
    "prompt": "<p>How many paragraphs does chunk 2 share with chunk 1?</p>",
    "choices": [
     "None — chunk 2 is just the long paragraph",
     "One — “Bring a stand.”, making chunk 2 exactly 71",
     "One — “Band camp.”",
     "Two — both short paragraphs"
    ],
    "answer": 0,
    "why": [
     null,
     "The separator is <code>\\n\\n</code>, two characters: 14 + 2 + 56 = 72, over 71. With a 1-character separator it would have fit.",
     "Popping always starts at the front, so “Band camp.” is the first to go.",
     "Chunk 1 is 26, over the overlap of 20, so at least one paragraph has to go."
    ],
    "solution": "<p>Atoms: 10, 14, 56.</p><p>Buffer 10 → 10 + 14 + 2 = 26. Atom 3: 26 + 56 + 2 = 84, over 71. <strong>Emit chunk 1 = 26.</strong></p><p>Pop while over 20: drop “Band camp.” → 26 − 10 − 2 = 14. The overlap test is satisfied, but atom 3 has to fit: 14 + 2 + 56 = <strong>72</strong>, over 71. Pop again → 0.</p><p><strong>Nothing shared.</strong> Chunks: 26 and 56. The 2-character separator made the difference.</p>",
    "doc": {
     "text": "Band camp.\n\nBring a stand.\n\nMarching drills run all afternoon on the practice field.",
     "sep": "\n\n",
     "size": 71,
     "overlap": 20
    }
   },
   {
    "topic": "Chunking edge cases",
    "prompt": "<p>A classmate says Split Text gave them chunks of <strong>40</strong> and <strong>62</strong> characters with Chunk Size <strong>50</strong>. No single line in their document is longer than 30 characters. What should you conclude?</p>",
    "choices": [
     "Nothing's wrong — Split Text often runs a little over when overlap is turned on",
     "Their Chunk Overlap must be set higher than 50",
     "They made a mistake — a chunk can only go over Chunk Size when a single atom is over it",
     "Nothing's wrong — the last chunk is allowed to run over"
    ],
    "answer": 2,
    "why": [
     "The popping keeps going until the next atom fits, so overlap can never push a chunk over the size.",
     "Overlap never overrides Chunk Size — Chunk Size wins.",
     null,
     "The last chunk follows the same rules as every other chunk."
    ],
    "solution": "<p>Chunk Size wins: after each emit, popping continues while the next atom won't fit. So the only way a chunk can be over the size is if one atom is over the size by itself — and here no line is over 30.</p><p>If your chunk is over the size and no atom is, <strong>recheck your popping</strong>.</p>"
   },
   {
    "topic": "Precision & recall in search",
    "prompt": "<p>A question has <strong>5 relevant</strong> sentences, and you set <strong>k = 5</strong>. The search gets <strong>4</strong> hits. What are the precision and recall?</p>",
    "choices": [
     "Precision 80%, recall 100%",
     "Precision 100%, recall 80%",
     "Precision 100%, recall 100%",
     "Precision 80%, recall 80%"
    ],
    "answer": 3,
    "why": [
     "Recall is 4 ÷ 5 — one relevant sentence was missed.",
     "Precision is 4 ÷ 5 — one of the five results was junk.",
     "100% on both is the <em>best possible</em> at this k. This search got 4, not 5.",
     null
    ],
    "solution": "<p>Precision = 4 ÷ 5 = 80%. Recall = 4 ÷ 5 = 80%.</p><p>When k equals the number of relevant sentences, the two fractions have the same top <em>and</em> the same bottom, so <strong>precision and recall are always equal</strong>.</p>"
   },
   {
    "topic": "Precision & recall in search",
    "prompt": "<p>Two students search the same 30-sentence collection for a question with <strong>4 relevant</strong> sentences.</p><ul><li><strong>Student One</strong> sets k = 8 and gets all 4: precision 50%, recall 100%.</li><li><strong>Student Two</strong> sets k = 5 and gets 3: precision 60%, recall 75%.</li></ul><p>Student Two says their search did the better job, since their precision is higher. Is that fair?</p>",
    "choices": [
     "Yes — higher precision means a better search",
     "No — Student One reached both ceilings (50% and 100%); Student Two missed both (80% and 100%)",
     "Yes — half of Student One's results were junk",
     "No — Student One's precision is really 4 ÷ 4 = 100%"
    ],
    "answer": 1,
    "why": [
     "Raw scores mean little without their ceilings. Student Two fell short of what k = 5 allowed.",
     null,
     "That junk was forced by k = 8: only 4 relevant sentences exist. It's a reason to lower k, not a failed search.",
     "4 ÷ 4 divides by relevant — that's recall. Precision divides by k: 4 ÷ 8."
    ],
    "solution": "<p>Student One: best hits = smaller of 8 and 4 = 4, so best precision = 4 ÷ 8 = 50% and best recall = 100%. They hit <strong>both</strong>.</p><p>Student Two: best hits = smaller of 5 and 4 = 4, so best precision = 4 ÷ 5 = 80% and best recall = 100%. They got 60% and 75% — short on both.</p>"
   }
  ]
 }
];
